<a href="https://colab.research.google.com/github/govardhan-06/practice-Notebooks/blob/main/Handling_Categorical_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### One-Hot Encoding

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv("train.csv")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
dataset=df["Sex"]
dataset

0        male
1      female
2      female
3      female
4        male
        ...
886      male
887    female
888    female
889      male
890      male
Name: Sex, Length: 891, dtype: object

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
dataset=pd.DataFrame(dataset)
dataset["Sex"]

0        male
1      female
2      female
3      female
4        male
        ...
886      male
887    female
888    female
889      male
890      male
Name: Sex, Length: 891, dtype: object

In [ ]:
dataset["Sex_Male"]=pd.get_dummies(dataset["Sex"],dtype=int,drop_first=True)
dataset.drop("Sex",inplace=True,axis=1)
dataset

     Sex_Male
0           1
1           0
2           0
3           0
4           1
..        ...
886         1
887         0
888         0
889         1
890         1

[891 rows x 1 columns]

In [ ]:
df=pd.read_csv("mercedes.csv",usecols=["X0","X1","X2","X3","X4","X5","X6"])
df.head()

   X0 X1  X2 X3 X4 X5 X6
0   k  v  at  a  d  u  j
1   k  t  av  e  d  y  l
2  az  w   n  c  d  x  j
3  az  t   n  f  d  x  l
4  az  v   n  f  d  h  d

### KDD Orange Cup Ensemble Selection for encoding categorical features

In [ ]:
for feature in df.columns:
    print(feature,":",len(df[feature].unique()))

X0 : 47
X1 : 27
X2 : 44
X3 : 7
X4 : 4
X5 : 29
X6 : 12

In [ ]:
for feature in df.columns:
  c=10
  top_categories=df[feature].value_counts().sort_values(ascending=False).head(10).index
  for category in top_categories:
    df[category]=np.where(df[feature]==category,1,0)
  df.drop(feature,axis=1,inplace=True)
df.head()

   z  ak  y  ay  t  x  o  f  n  w  ...  ai  m  e  d  g  q  p  j  h  k
0  0   0  0   0  0  0  0  0  0  0  ...   0  0  0  0  0  0  0  1  0  0
1  0   0  0   0  0  0  0  0  0  0  ...   0  0  1  0  0  0  0  0  0  0
2  0   0  0   0  0  0  0  0  0  0  ...   0  0  0  0  0  0  0  1  0  0
3  0   0  0   0  0  0  0  1  0  0  ...   0  0  0  0  0  0  0  0  0  0
4  0   0  0   0  0  0  0  1  0  0  ...   0  0  0  1  0  0  0  0  0  0

[5 rows x 31 columns]

In [ ]:
pd.set_option("display.max_columns",None)
df.head()

,z,ak,y,ay,t,x,o,f,n,w,aa,s,b,l,v,r,i,a,c,as,ae,ai,m,e,d,g,q,p,j,h,k
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
3,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0

### Frequency Encoding

In [32]:
train_set = pd.read_csv('http://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data' , header = None,index_col=None)
train_set.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [34]:
columns=[1,3,5,6,7,8,9,13]
train_set=train_set[columns]

In [35]:
train_set.columns=['Employment','Degree','Martial_Status','Designation','Family_job','Race','Sex','Country']
train_set

,Employment,Degree,Martial_Status,Designation,Family_job,Race,Sex,Country
0,State-gov,Bachelors,Never-married,Adm-clerical,Not-in-family,White,Male,United-States
1,Self-emp-not-inc,Bachelors,Married-civ-spouse,Exec-managerial,Husband,White,Male,United-States
2,Private,HS-grad,Divorced,Handlers-cleaners,Not-in-family,White,Male,United-States
3,Private,11th,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,United-States
4,Private,Bachelors,Married-civ-spouse,Prof-specialty,Wife,Black,Female,Cuba
...,...,...,...,...,...,...,...,...
32556,Private,Assoc-acdm,Married-civ-spouse,Tech-support,Wife,White,Female,United-States
32557,Private,HS-grad,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,United-States
32558,Private,HS-grad,Widowed,Adm-clerical,Unmarried,White,Female,United-States
32559,Private,HS-grad,Never-married,Adm-clerical,Own-child,White,Male,United-States
32560,Self-emp-inc,HS-grad,Married-civ-spouse,Exec-managerial,Wife,White,Female,United-States

In [36]:
train_set["Country"]

0         United-States
1         United-States
2         United-States
3         United-States
4                  Cuba
              ...
32556     United-States
32557     United-States
32558     United-States
32559     United-States
32560     United-States
Name: Country, Length: 32561, dtype: object

In [40]:
top=train_set["Country"].value_counts().to_dict()
top

{' United-States': 29170,
 ' Mexico': 643,
 ' ?': 583,
 ' Philippines': 198,
 ' Germany': 137,
 ' Canada': 121,
 ' Puerto-Rico': 114,
 ' El-Salvador': 106,
 ' India': 100,
 ' Cuba': 95,
 ' England': 90,
 ' Jamaica': 81,
 ' South': 80,
 ' China': 75,
 ' Italy': 73,
 ' Dominican-Republic': 70,
 ' Vietnam': 67,
 ' Guatemala': 64,
 ' Japan': 62,
 ' Poland': 60,
 ' Columbia': 59,
 ' Taiwan': 51,
 ' Haiti': 44,
 ' Iran': 43,
 ' Portugal': 37,
 ' Nicaragua': 34,
 ' Peru': 31,
 ' France': 29,
 ' Greece': 29,
 ' Ecuador': 28,
 ' Ireland': 24,
 ' Hong': 20,
 ' Cambodia': 19,
 ' Trinadad&Tobago': 19,
 ' Laos': 18,
 ' Thailand': 18,
 ' Yugoslavia': 16,
 ' Outlying-US(Guam-USVI-etc)': 14,
 ' Honduras': 13,
 ' Hungary': 13,
 ' Scotland': 12,
 ' Holand-Netherlands': 1}

In [42]:
train_set["Country"]=train_set["Country"].map(top)
train_set.head(20)

,Employment,Degree,Martial_Status,Designation,Family_job,Race,Sex,Country
0,State-gov,Bachelors,Never-married,Adm-clerical,Not-in-family,White,Male,NaN
1,Self-emp-not-inc,Bachelors,Married-civ-spouse,Exec-managerial,Husband,White,Male,NaN
2,Private,HS-grad,Divorced,Handlers-cleaners,Not-in-family,White,Male,NaN
3,Private,11th,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,NaN
4,Private,Bachelors,Married-civ-spouse,Prof-specialty,Wife,Black,Female,NaN
5,Private,Masters,Married-civ-spouse,Exec-managerial,Wife,White,Female,NaN
6,Private,9th,Married-spouse-absent,Other-service,Not-in-family,Black,Female,NaN
7,Self-emp-not-inc,HS-grad,Married-civ-spouse,Exec-managerial,Husband,White,Male,NaN
8,Private,Masters,Never-married,Prof-specialty,Not-in-family,White,Female,NaN
9,Private,Bachelors,Married-civ-spouse,Exec-managerial,Husband,White,Male,NaN
10,Private,Some-college,Married-civ-spouse,Exec-managerial,Husband,Black,Male,NaN
11,State-gov,Bachelors,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,NaN
12,Private,Bachelors,Never-married,Adm-clerical,Own-child,White,Female,NaN
13,Private,Assoc-acdm,Never-married,Sales,Not-in-family,Black,Male,NaN
14,Private,Assoc-voc,Married-civ-spouse,Craft-repair,Husband,Asian-Pac-Islander,Male,NaN
15,Private,7th-8th,Married-civ-spouse,Transport-moving,Husband,Amer-Indian-Eskimo,Male,NaN
16,Self-emp-not-inc,HS-grad,Never-married,Farming-fishing,Own-child,White,Male,NaN
17,Private,HS-grad,Never-married,Machine-op-inspct,Unmarried,White,Male,NaN
18,Private,11th,Married-civ-spouse,Sales,Husband,White,Male,NaN
19,Self-emp-not-inc,Masters,Divorced,Exec-managerial,Unmarried,White,Female,NaN

### Target guided Ordinal Mapping

In [62]:
df=pd.read_csv("train.csv")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [63]:
df["Cabin"]=df["Cabin"].fillna("Missing")

In [64]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin            0
Embarked         2
dtype: int64

In [65]:
df["Cabin"]=[i[0] for i in df["Cabin"]]

In [66]:
df.groupby(["Cabin"])["Survived"].mean()

Cabin
A    0.466667
B    0.744681
C    0.593220
D    0.757576
E    0.750000
F    0.615385
G    0.500000
M    0.299854
T    0.000000
Name: Survived, dtype: float64

In [67]:
df["Cabin"].unique()

array(['M', 'C', 'E', 'G', 'D', 'A', 'B', 'F', 'T'], dtype=object)

In [68]:
df["Cabin_Ordinal"]=df["Cabin"].map(df["Cabin"].value_counts().to_dict())

In [69]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Cabin_Ordinal
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,M,S,687
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,C,59
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,M,S,687
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C,S,59
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,M,S,687
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,M,S,687
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B,S,47
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,M,S,687
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C,C,59
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,M,Q,687

In [82]:
df["Cabin_Mean"]=df["Cabin"].map(df.groupby(df['Cabin'])["Survived"].mean().to_dict())

In [83]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Cabin_Ordinal,Cabin_Mean
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,M,S,687,0.299854
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,C,59,0.593220
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,M,S,687,0.299854
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C,S,59,0.593220
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,M,S,687,0.299854
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,M,S,687,0.299854
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B,S,47,0.744681
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,M,S,687,0.299854
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C,C,59,0.593220
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,M,Q,687,0.299854

### Probability Ratio Encoding

In [87]:
df=pd.read_csv("train.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [91]:
df["Cabin"]=df["Cabin"].fillna("Missing")

In [96]:
df["Cabin"]=[i[0] for i in df["Cabin"]]

In [97]:
df["Cabin"].value_counts()

Cabin
M    687
C     59
B     47
D     33
E     32
A     15
F     13
G      4
T      1
Name: count, dtype: int64

In [113]:
prob=df.groupby(["Cabin"])["Survived"].mean()
prob

Cabin
A    0.466667
B    0.744681
C    0.593220
D    0.757576
E    0.750000
F    0.615385
G    0.500000
M    0.299854
T    0.000000
Name: Survived, dtype: float64

In [115]:
prob_df=pd.DataFrame(prob)

In [117]:
prob_df["Died"]=1-prob_df["Survived"]

In [118]:
prob_df

       Survived      Died
Cabin
A      0.466667  0.533333
B      0.744681  0.255319
C      0.593220  0.406780
D      0.757576  0.242424
E      0.750000  0.250000
F      0.615385  0.384615
G      0.500000  0.500000
M      0.299854  0.700146
T      0.000000  1.000000

In [129]:
prob_df["Probability"]=prob_df["Survived"]/prob_df["Died"]
x=prob_df["Probability"].to_dict()

In [130]:
x

{'A': 0.875,
 'B': 2.916666666666666,
 'C': 1.4583333333333333,
 'D': 3.125,
 'E': 3.0,
 'F': 1.6000000000000003,
 'G': 1.0,
 'M': 0.42827442827442824,
 'T': 0.0}

In [131]:
prob_df

       Survived      Died  Probability
Cabin
A      0.466667  0.533333     0.875000
B      0.744681  0.255319     2.916667
C      0.593220  0.406780     1.458333
D      0.757576  0.242424     3.125000
E      0.750000  0.250000     3.000000
F      0.615385  0.384615     1.600000
G      0.500000  0.500000     1.000000
M      0.299854  0.700146     0.428274
T      0.000000  1.000000     0.000000

In [133]:
df['Cabin']=df['Cabin'].map(x)

In [137]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,0.428274,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,1.458333,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,0.428274,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,1.458333,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,0.428274,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,0.428274,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,2.916667,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,0.428274,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,1.458333,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,0.428274,Q